services:
  mysql:
    image: mysql:8.0
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: sickpassword
      MYSQL_DATABASE: pbuild_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: lostborders/pbuild-api:latest
    ports:
      - "5286:5286"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mysql
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: "300"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
    restart: unless-stopped

volumes:
  mysql_data: