services:
  backend:
    image: lostborders/pbuild-api:latest
    network_mode: host
    ports:
      - 5286:5286


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    environment:
      WATCHTOWER_POLL_INTERVAL: "10"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_CLEANUP: "true"
