name: CI - Docker Build & Tests on Dev Branch

on:
  push:
    branches:
      - dev 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t pbuild-backend .

      - name: Run Unit Tests Inside Docker
        run: docker run --rm pbuild-backend dotnet test --no-build --configuration Release --verbosity normal
