name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run tests in Docker
        run: |
          docker build --target build --tag pbuild-backend .
          
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm pbuild-backend dotnet-sonarscanner begin /k:"duradenzel_pbuild-backend" /o:"duradenzel" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          
          docker run --rm pbuild-backend dotnet build
          
          docker run --rm pbuild-backend dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
