name: Build and Test With Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore pbuild.sln

      - name: Build solution
        run: dotnet build pbuild.sln --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet test pbuild-tests/pbuild-tests.csproj \
            --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory pbuild-tests/TestResults \
            --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: pbuild-tests/TestResults/test_results.trx

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: pbuild-tests/TestResults/**/coverage.cobertura.xml

          


      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate HTML coverage report
        run: |
          reportgenerator \
            -reports:pbuild-tests/TestResults/**/coverage.cobertura.xml \
            -targetdir:coverage-report-html \
            -reporttypes:Html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage-report-html

