name: .NET Build and Test with Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install SonarScanner tool
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin \
          /k:"duradenzel:pbuild-backend" \
          /o:"duradenzel" \
          /d:sonar.login="${SONAR_TOKEN}" \
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/*.opencover.xml"

    - name: Restore dependencies
      run: dotnet restore pbuild.sln

    - name: Build the solution
      run: dotnet build pbuild.sln --configuration Release --no-restore

    - name: Run tests with OpenCover format code coverage
      run: |
        dotnet test pbuild-tests/pbuild-tests.csproj \
          --no-build \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --logger:"trx;LogFileName=test_results.trx" \
          --results-directory ./TestResults

    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner end /d:sonar.login="${SONAR_TOKEN}"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults/**/*.trx

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./TestResults/**/*.opencover.xml
